import { sidebar } from "vuepress-theme-hope";

export default sidebar([
  "/",
  {
    text: "MIT 6.1200J 笔记",
    collapsible: true,
    prefix: "/lecture-notes-zh/",
    children: [
      "lec01",
      "lec02",
      "lec03",
      "lec04",
      "lec05",
      "lec06",
      "lec07",
      "lec08",
      "lec09",
      "lec10",
      "lec11",
      "lec12",
      "lec13",
      "lec14",
      "lec15",
      "lec16",
      "lec17",
      "lec18",
      "lec19",
      "lec20",
      "lec21",
      "lec22",
      "lec24",
    ],
  },
  {
    text: "xv6-riscv-book",
    collapsible: true,
    prefix: "/xv6-riscv-book/",
    children: [
      "",
      "chapter1/",
      "chapter2/",
      "chapter3/",
      "chapter4/",
      "chapter5/",
      "chapter6/",
      "chapter7/",
      "chapter8/",
      "chapter9/",
    ],
  },
]);
