import { sidebar } from "vuepress-theme-hope";

export default sidebar([
  "/",
  {
    text: "MIT 6.1200J 笔记",
    collapsible: true,
    prefix: "/lecture-notes-zh/",
    children: [
      "lec01",
      "lec02",
      "lec03",
      "lec04",
      "lec05",
      "lec06",
      "lec07",
      "lec08",
      "lec09",
      "lec10",
      "lec11",
      "lec12",
      "lec13",
      "lec14",
      "lec15",
      "lec16",
      "lec17",
      "lec18",
      "lec19",
      "lec20",
      "lec21",
      "lec22",
      "lec24",
    ],
  },
  {
    text: "xv6-riscv-book",
    collapsible: true,
    prefix: "/xv6-riscv-book/",
    children: [
      "",
      "chapter1/",
      "chapter2/",
      "chapter3/",
      "chapter4/",
      "chapter5/",
      "chapter6/",
      "chapter7/",
      "chapter8/",
      "chapter9/",
    ],
  },
  {
    text: "CS110 课件笔记",
    collapsible: true,
    prefix: "/slides-zh/",
    children: [
      "01-summary/",
      "02-summary/",
      "03-summary/",
      "04-summary/",
      "05-summary/",
      "06-summary/",
      "07-summary/",
      "08-summary/",
      "09-summary/",
      "10-summary/",
      "11-summary/",
      "12-summary/",
      "13-summary/",
      "14-summary/",
      "15-summary/",
      "16-summary/",
      "17-summary/",
      "18-summary/",
      "19-summary/",
      "20-summary/",
    ],
  },
  {
    text: "CS106L 课程笔记",
    collapsible: true,
    prefix: "/translated_markdown/",
    children: [
      "01-Welcome/",
      "02-TypesAndStructs/",
      "03-InitializationAndReferences/",
      "04-Streams/",
      "05-Containers/",
      "06-Iterators/",
      "07-Classes/",
      "08-Inheritance/",
      "09-TemplateClasses/",
      "10-TemplateFunctions/",
      "11-FunctionsAndLambdas/",
      "12-OperatorOverloading/",
      "13-SpecialMemberFunctions/",
      "14-MoveSemantics/",
      "15-OptionalAndTypeSafety/",
      "16-RAII-SmartPointers/",
      "17-UnitTesting/",
    ],
  },
]);
