import { sidebar } from "vuepress-theme-hope";

export default sidebar([
  "/",
  {
    text: "MIT 6.1200J 笔记",
    collapsible: true,
    prefix: "/lecture-notes-zh/",
    children: [
      "lec01",
      "lec02",
      "lec03",
      "lec04",
      "lec05",
      "lec06",
      "lec07",
      "lec08",
      "lec09",
      "lec10",
      "lec11",
      "lec12",
      "lec13",
      "lec14",
      "lec15",
      "lec16",
      "lec17",
      "lec18",
      "lec19",
      "lec20",
      "lec21",
      "lec22",
      "lec24",
    ],
  },
  {
    text: "xv6-riscv-book",
    collapsible: true,
    prefix: "/xv6-riscv-book/",
    children: [
      "",
      "chapter1/",
      "chapter2/",
      "chapter3/",
      "chapter4/",
      "chapter5/",
      "chapter6/",
      "chapter7/",
      "chapter8/",
      "chapter9/",
    ],
  },
  {
    text: "CS110 课件笔记",
    collapsible: true,
    prefix: "/slides-zh/",
    children: [
      { text: "欢迎来到 CS110：计算机系统原理", link: "01-summary/" },
      { text: "UNIX 文件系统 API 与系统调用", link: "02-summary/" },
      { text: "异常控制流：中断、故障与陷阱", link: "03-summary/" },
      { text: "多进程入门：fork 系统调用", link: "04-summary/" },
      { text: "深入 fork：进程创建与管理", link: "05-summary/" },
      { text: "信号处理与进程同步基础", link: "06-summary/" },
      { text: "进程管理：waitpid 与退出状态", link: "07-summary/" },
      { text: "多进程收尾：SIGCHLD 与信号同步", link: "08-summary/" },
      { text: "虚拟内存与多线程入门", link: "09-summary/" },
      { text: "多线程编程：竞争条件与修复", link: "10-summary/" },
      { text: "线程与并发：哲学家就餐问题", link: "11-summary/" },
      { text: "条件变量与信号量", link: "12-summary/" },
      { text: "并发综合：冰淇淋店模拟", link: "13-summary/" },
      { text: "网络编程入门：Socket 与时间服务器", link: "14-summary/" },
      { text: "HTTP 协议与 Web 客户端实现", link: "15-summary/" },
      { text: "Socket 底层实现与服务器架构", link: "16-summary/" },
      { text: "MapReduce 编程模型", link: "17-summary/" },
      { text: "MapReduce 实现与系统设计原则", link: "18-summary/" },
      { text: "非阻塞 I/O", link: "19-summary/" },
      { text: "课程总结与期末考试信息", link: "20-summary/" },
    ],
  },
  {
    text: "CS106L 课程笔记",
    collapsible: true,
    prefix: "/translated_markdown/",
    children: [
      "01-Welcome/",
      "02-TypesAndStructs/",
      "03-InitializationAndReferences/",
      "04-Streams/",
      "05-Containers/",
      "06-Iterators/",
      "07-Classes/",
      "08-Inheritance/",
      "09-TemplateClasses/",
      "10-TemplateFunctions/",
      "11-FunctionsAndLambdas/",
      "12-OperatorOverloading/",
      "13-SpecialMemberFunctions/",
      "14-MoveSemantics/",
      "15-OptionalAndTypeSafety/",
      "16-RAII-SmartPointers/",
      "17-UnitTesting/",
    ],
  },
]);
